/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_cognito_identity_pool_id:
    "ap-northeast-1:eeb6a284-b1a3-42c1-adbe-4ac03284ef9a",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_s1m87CP70",
  aws_user_pools_web_client_id: "5bki5g11trdca7i3ltfu8t86rn",
  oauth: {},
};

export default awsmobile;
